-- Read the docs: https://www.lunarvim.org/docs/configuration
-- Video Tutorials: https://www.youtube.com/watch?v=sFA9kX-Ud_c&list=PLhoH5vyxr6QqGu0i7tt_XoVK9v-KvZ3m6
-- Forum: https://www.reddit.com/r/lunarvim/
-- Discord: https://discord.com/invite/Xb9B4Ny

lvim.format_on_save = true
vim.g.mapleader = " "
lvim.keys.normal_mode["d"] = "g"
lvim.keys.normal_mode["e"] = "k"
lvim.keys.normal_mode["f"] = "e"
lvim.keys.normal_mode["g"] = "t"
lvim.keys.normal_mode["i"] = "l"
lvim.keys.normal_mode["j"] = "y"
lvim.keys.normal_mode["k"] = "n"
lvim.keys.normal_mode["l"] = "u"
lvim.keys.normal_mode["n"] = "j"
lvim.keys.normal_mode["o"] = "p"
lvim.keys.normal_mode["p"] = "r"
lvim.keys.normal_mode["r"] = "s"
lvim.keys.normal_mode["s"] = "d"
lvim.keys.normal_mode["t"] = "f"
lvim.keys.normal_mode["u"] = "i"
lvim.keys.normal_mode["y"] = "o"
lvim.keys.normal_mode["D"] = "G"
lvim.keys.normal_mode["E"] = "K"
lvim.keys.normal_mode["F"] = "E"
lvim.keys.normal_mode["G"] = "T"
lvim.keys.normal_mode["I"] = "L"
lvim.keys.normal_mode["J"] = "Y"
lvim.keys.normal_mode["K"] = "N"
lvim.keys.normal_mode["L"] = "U"
lvim.keys.normal_mode["N"] = "J"
lvim.keys.normal_mode["O"] = "P"
lvim.keys.normal_mode["P"] = "R"
lvim.keys.normal_mode["R"] = "S"
lvim.keys.normal_mode["S"] = "D"
lvim.keys.normal_mode["T"] = "F"
lvim.keys.normal_mode["U"] = "I"
lvim.keys.normal_mode["Y"] = "O"
